sudo: required
services:
  - docker

before_install:
  - docker build -t mydockeridlili/multicontainer -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mydockeridlili/react-test npm test

after_success:
  - docker build -t mydockeridlili/multicontainer ./client
  - docker build -t mydockeridlili/multicontainer ./nginx
  - docker build -t mydockeridlili/multicontainer ./server
  - docker build -t mydockeridlili/multicontainer ./worker 
  # Login in the docker CLI
  - echo "$DOCKER_PASSWOER" | docker login -u "DOCKER_ID" --password-stdin
  - docker push mydockeridlili/multicontainer-client
  - docker push mydockeridlili/multicontainer-nginx
  - docker push mydockeridlili/multicontainer-server
  - docker push mydockeridlili/multicontainer-worker
