sudo: required
services:
  - docker

before_install:
  - docker build -t LiliyaBurlakova/multicontainer -f Dockerfile.dev .

script:
  - docker run -e CI=true LiliyaBurlakova/react-test npm test

after_success:
  - docker build -t LiliyaBurlakova/multicontainer ./client
  - docker build -t LiliyaBurlakova/multicontainer ./nginx
  - docker build -t LiliyaBurlakova/multicontainer ./server
  - docker build -t LiliyaBurlakova/multicontainer ./worker 
  # Login in the docker CLI
  - echo "$DOCKER_PASSWOER" | docker login -u "DOCKER_ID" --password-stdin
  - docker push mydockerid/multicontainer-client
  - docker push mydockerid/multicontainer-nginx
  - docker push mydockerid/multicontainer-server
  - docker push mydockerid/multicontainer-worker
