sudo: required
services:
  - docker

before_install:
  - docker build -t mydockeridlili/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mydockeridlili/complex npm test

after_success:
  - docker build -t mydockeridlili/complex ./client
  - docker build -t mydockeridlili/complex ./nginx
  - docker build -t mydockeridlili/complex ./server
  - docker build -t mydockeridlili/complex ./worker 
  # Login in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mydockeridlili/complex-client
  - docker push mydockeridlili/complex-nginx
  - docker push mydockeridlili/complex-server
  - docker push mydockeridlili/complex-worker
